name: CI

on:
  push:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Checkout scm
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Install
      run: |
        npm install

    - name: Build and test
      run: |
        npm test
        npm run build

    - name: Code coverage
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN} -f coverage/coverage-final.json -Z